export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
export const ERROR = 'ERROR'

export const GO_TO_LOGIN = 'GO_TO_LOGIN'
export const GO_TO_SETTINGS = 'GO_TO_SETTINGS'

export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LIP_SIGNIN_FAILED = 'LIP_SIGNIN_FAILED'
export const LIP_SIGNIN_SUCCESS = 'LIP_SIGNIN_SUCCESS'

export const BACKEND_SIGNIN_SUCCESS = 'BACKEND_SIGNIN_SUCCESS'
export const BACKEND_SIGNIN_FAILED = 'BACKEND_SIGNIN_FAILED'

export const GET_IDS_SUCCESS = 'GET_IDS_SUCCESS'
export const GET_IDS_FAILED = 'GET_IDS_FAILED'

export const DEVICE_RETRIEVAL_SUCCESS = 'DEVICE_RETRIEVAL_SUCCESS'
export const DEVICE_RETRIEVAL_FAILED = 'DEVICE_RETRIEVAL_FAILED'

export const TABASCO_TOKENS_SUCCESS = 'TABASCO_TOKENS_SUCCESS'
export const TABASCO_TOKENS_FAILED = 'TABASCO_TOKENS_FAILED'

export const WS_REQUEST_FAILED = 'WS_REQUEST_FAILED'
export const WS_REQUEST_SUCCESS = 'WS_REQUEST_SUCCESS'

export const LOGIN_ACTION = 'LOGIN_ACTION'
export const GET_DEVICES_ACTION = 'GET_DEVICES_ACTION'
export const PING_HUB = 'PING_HUB'
export const START_WEBSOCKET_ACTION = 'START_WEBSOCKET_ACTION'
export const WS_REQUEST_ACTION = 'WS_REQUEST_ACTION'
export const WS_EVENT_RCVD = 'WS_EVENT_RCVD'