export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
export const ERROR = 'ERROR'

export const GO_TO_LOGIN = 'GO_TO_LOGIN'
export const GO_TO_SETTINGS = 'GO_TO_SETTINGS'

export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LIP_SIGNIN_FAILED = 'LIP_SIGNIN_FAILED'
export const LIP_SIGNIN_SUCCESS = 'LIP_SIGNIN_SUCCESS'

export const BACKEND_SIGNIN_SUCCESS = 'BACKEND_SIGNIN_SUCCESS'
export const BACKEND_SIGNIN_FAILED = 'BACKEND_SIGNIN_FAILED'

export const GET_PROVISION_INFO_FAILED = 'GET_PROVISION_INFO_FAILED'
export const GET_PROVISION_INFO_SUCCESS = 'GET_PROVISION_INFO_SUCCESS'

export const DEVICE_RETRIEVAL_SUCCESS = 'DEVICE_RETRIEVAL_SUCCESS'
export const DEVICE_RETRIEVAL_FAILED = 'DEVICE_RETRIEVAL_FAILED'

export const LOGIN_ACTION = 'LOGIN_ACTION'
export const GET_DEVICES_ACTION = 'GET_DEVICES_ACTION'